### PR TITLE
Move requirements.txt to requirements-dev.txt

### PR DESCRIPTION
**Pull request by nlopes**
Python (user) convention uses requirements-dev.txt for all the minimum dependencies
required to set the local workspace.

I also took the liberty to install the minimum ones to be able to fully run all tests.

### CODE REVIEW

**Review by jesse-c — COMMENTED** [review]
Do we not need both? Does Dependant need to track this file too?

image

**Comment by nlopes** [comment]
I could swear that Dependabot could track changes in any file that has `dev` in the name too but this is a good point.
Let me take a look.

**Comment by nlopes** [comment]
> I could swear that Dependabot could track changes in any file that has `dev` in the name too but this is a good point. Let me take a look.

I think this https://github.com/dependabot/dependabot-core/commit/98503905edd191bafd1a701e8eb698175d867edd means it should work just fine.

**Review by jesse-c — APPROVED** [review]
Nice, that's good to know.

**Comment by nlopes** [comment]
> Nice, that's good to know.

If it doesn't work, we can revisit. Happy to change back to `requirements.txt` if dependabot doesn't pick up on this one.

**Comment by sgerrand** [comment]
> if dependabot doesn't pick up on this one.

Looks like #57, #58, #59 and #60 say that the Dependabot setup was unaffected.

**Pull request merged**
